# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='url',
        ),
        migrations.AddField(
            model_name='staticpage',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
