# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20171128_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default='True')),
                ('ac_degree', models.CharField(max_length=50)),
                ('ac_title', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('work_start_date', models.DateField(null=True)),
                ('work_spec_start_date', models.DateField(null=True)),
                ('training', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StaffCategory'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
