# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171130_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='staffcategory',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ac_degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ac_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='education',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffcategory',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='discipline',
            name='educator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Staff'),
        ),
    ]
