# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='educator',
        ),
        migrations.AddField(
            model_name='discipline',
            name='educator',
            field=models.ManyToManyField(to='main.Staff'),
        ),
    ]
