# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171202_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('weight', models.IntegerField(default=0, verbose_name='\u0412\u0435\u0441')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Menu', verbose_name='\u041c\u0435\u043d\u044e')),
                ('parent_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MenuItem', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0438\u0439 \u044d\u043b\u0435\u043c\u0435\u043d\u0442')),
            ],
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='add_to_menu',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='weight',
        ),
        migrations.AddField(
            model_name='staticpage',
            name='published',
            field=models.BooleanField(default='False', verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='add_to',
            field=models.ManyToManyField(to='main.MenuItem', verbose_name='\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0432...'),
        ),
    ]
