# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_menuitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
