# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20171213_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add_to',
            field=models.ManyToManyField(to='main.MenuItem', verbose_name='\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0432...'),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default='False', verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e'),
        ),
    ]
